In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('FinancialAnalysis.csv')

In [7]:
df.head()

,Year,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities.,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,2023,Microsoft,211915.0,72361.0,411976.0,205753.0,87582.0,NaN,NaN,NaN,NaN,NaN
1,2022,Microsoft,198270.0,72738.0,364840.0,198298.0,89035.0,NaN,NaN,NaN,NaN,NaN
2,2021,Microsoft,168088.0,61271.0,333779.0,191791.0,76740.0,NaN,NaN,NaN,NaN,NaN
3,2023,Tesla,96773.0,14974.0,106618.0,43009.0,13256.0,NaN,NaN,NaN,NaN,NaN
4,2022,Tesla,81462.0,12587.0,82338.0,36440.0,14724.0,NaN,NaN,NaN,NaN,NaN

In [9]:
df['Revenue Growth (%)'] = df.groupby(['Company'])['Total Revenue'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby(['Company'])[' Net Income'].pct_change() * 100

In [12]:
df.rename(columns={' Net Income': 'Net Income'}, inplace=True)
df.rename(columns={' Total Assets': 'Total Assets'}, inplace=True)
df.rename(columns={' Total Liabilities': 'Total Liabilities'}, inplace=True)

In [13]:
df['Assets Growth (%)'] = df.groupby(['Company'])['Total Assets'].pct_change() * 100
df['Libailities Growth (%)'] = df.groupby(['Company'])['Total Liabilities'].pct_change() * 100
df['CFO Growth (%)'] = df.groupby(['Company'])['Cash Flow from Operating Activities.'].pct_change() * 100

In [14]:
df.head()

,Year,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities.,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Libailities Growth (%),CFO Growth (%)
0,2023,Microsoft,211915.0,72361.0,411976.0,205753.0,87582.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,Microsoft,198270.0,72738.0,364840.0,198298.0,89035.0,NaN,NaN,NaN,NaN,NaN,-6.438902,0.520999,-11.441443,-3.623276,1.659017
2,2021,Microsoft,168088.0,61271.0,333779.0,191791.0,76740.0,NaN,NaN,NaN,NaN,NaN,-15.222676,-15.764800,-8.513595,-3.281425,-13.809176
3,2023,Tesla,96773.0,14974.0,106618.0,43009.0,13256.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022,Tesla,81462.0,12587.0,82338.0,36440.0,14724.0,NaN,NaN,NaN,NaN,NaN,-15.821562,-15.940964,-22.772890,-15.273547,11.074231

In [15]:
df = df.loc[:, ~df.columns.str.startswith('Unnamed')]

In [16]:
df.head()

,Year,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities.,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Libailities Growth (%),CFO Growth (%)
0,2023,Microsoft,211915.0,72361.0,411976.0,205753.0,87582.0,NaN,NaN,NaN,NaN,NaN
1,2022,Microsoft,198270.0,72738.0,364840.0,198298.0,89035.0,-6.438902,0.520999,-11.441443,-3.623276,1.659017
2,2021,Microsoft,168088.0,61271.0,333779.0,191791.0,76740.0,-15.222676,-15.764800,-8.513595,-3.281425,-13.809176
3,2023,Tesla,96773.0,14974.0,106618.0,43009.0,13256.0,NaN,NaN,NaN,NaN,NaN
4,2022,Tesla,81462.0,12587.0,82338.0,36440.0,14724.0,-15.821562,-15.940964,-22.772890,-15.273547,11.074231

In [17]:
df.fillna(0, inplace=True)

<ipython-input-17-a616889d5bf1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)

In [18]:
df.head()

,Year,Company,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities.,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Libailities Growth (%),CFO Growth (%)
0,2023,Microsoft,211915.0,72361.0,411976.0,205753.0,87582.0,0.000000,0.000000,0.000000,0.000000,0.000000
1,2022,Microsoft,198270.0,72738.0,364840.0,198298.0,89035.0,-6.438902,0.520999,-11.441443,-3.623276,1.659017
2,2021,Microsoft,168088.0,61271.0,333779.0,191791.0,76740.0,-15.222676,-15.764800,-8.513595,-3.281425,-13.809176
3,2023,Tesla,96773.0,14974.0,106618.0,43009.0,13256.0,0.000000,0.000000,0.000000,0.000000,0.000000
4,2022,Tesla,81462.0,12587.0,82338.0,36440.0,14724.0,-15.821562,-15.940964,-22.772890,-15.273547,11.074231

In [19]:
print(df.to_string())

   Year    Company  Total Revenue  Net Income  Total Assets  Total Liabilities  Cash Flow from Operating Activities.  Revenue Growth (%)  Net Income Growth (%)  Assets Growth (%)  Libailities Growth (%)  CFO Growth (%)
0  2023  Microsoft       211915.0     72361.0      411976.0           205753.0                               87582.0            0.000000               0.000000           0.000000                0.000000        0.000000
1  2022  Microsoft       198270.0     72738.0      364840.0           198298.0                               89035.0           -6.438902               0.520999         -11.441443               -3.623276        1.659017
2  2021  Microsoft       168088.0     61271.0      333779.0           191791.0                               76740.0          -15.222676             -15.764800          -8.513595               -3.281425      -13.809176
3  2023      Tesla        96773.0     14974.0      106618.0            43009.0                               13256.0            0.000000               0.000000           0.000000                0.000000        0.000000
4  2022      Tesla        81462.0     12587.0       82338.0            36440.0                               14724.0          -15.821562             -15.940964         -22.772890              -15.273547       11.074231
5  2021      Tesla        53823.0      5644.0       62131.0            30548.0                               11497.0          -33.928703             -55.160086         -24.541524              -16.169045      -21.916599
6  2023      Apple       383285.0     96995.0      352583.0           290437.0                              110543.0            0.000000               0.000000           0.000000                0.000000        0.000000
7  2022      Apple       394328.0     99803.0      352755.0           302083.0                              122151.0            2.881146               2.894995           0.048783                4.009820       10.500891
8  2021      Apple       365817.0     94680.0      351002.0           287912.0                              104038.0           -7.230275              -5.133112          -0.496945               -4.691095      -14.828368

**Revenue and Net Income Trends:**

1. Microsoft shows consistent growth in revenue and net income over the years, though some fluctuations in growth percentages indicate varying business performance in different fiscal years.
2. Tesla has a remarkable increase in revenue and net income over the years, demonstrating its rapid growth and expansion in the electric vehicle market.
3. Apple maintains strong revenue and net income figures, indicating steady growth and solid market performance.

**Asset and Liability Management:**

1. Microsoft's assets and liabilities have been increasing steadily, reflecting its investments in technology and expansion efforts.
2. Tesla's total assets have grown significantly, though it also has seen substantial increases in liabilities, typical for a company in an expansion phase.
3. Apple shows substantial total assets with relatively stable growth in liabilities, indicating effective asset management and financial stability.

**Cash Flow from Operating Activities:**

1. Microsoft maintains a strong cash flow from operating activities, indicative of its robust core business operations.
2. Tesla's cash flow from operating activities has seen impressive growth, reflecting its operational efficiency improvements as it scales production.
3. Apple consistently generates high cash flow from operating activities, showcasing its strong market position and operational efficiency.

**Growth Percentages:**

1. he growth percentages for revenue, net income, assets, liabilities, and CFO provide insights into each company's financial health and growth trajectory.
2. Negative growth percentages in certain years highlight challenges or adjustments in company strategies.

**Conclusion**
The dataset reveals valuable insights into the financial health and performance of Microsoft, Tesla, and Apple over recent years. Microsoft shows consistent and robust financial performance, Tesla exhibits rapid growth indicative of a company scaling quickly, and Apple demonstrates strong market leadership with substantial revenues and effective financial management. Analyzing these metrics provides a comprehensive view of how these technology giants are evolving in a dynamic market environment.